### ISSUE TITLE
Add option to store all config settings for --rpc, etc. in config.toml

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#172]
Starting it from the command line should come with reasonable defaults in the form of a config.toml file.

**Comment by greg-szabo** [comment]
Currently on the full node side this is how you start up ethermint:
```ethermint --datadir=$SOMEHOME --rpc -- rpcaddr=0.0.0.0 ws - wsaddr=0.0.0.0  -- rpcapi eth,net,web3,personal,admin```

On the validator side it's enough to say:
```ethermint --datadir=$SOMEHOME```

The problem is that when you install ethermint from a package, you don't know if the user is going to start it as a full node or a validator. The system service cannot change the command-line parameters so the user has to change them. This is very inconvenient for the user, it should not be expected for them to change system services for a configuration.
The easy solution is to read a configuration file (or even environment variables) to parameterize the binary. This way the system command is always the same, but the configuration can be easily changed by the user.

The optimal command the system service should run would be:
```ethermint --datadir=$SOMEHOME```
or alternatively:
```ethermint --datadir=$SOMEHOME --config=$SOMEHOME/alternateconfig```
