### ISSUE TITLE
Implement and publish performance and capacity numbers

### ISSUE THREAD

**Issue by illya13** [cosmos/ethermint-archive#174]
# Performance
for a given:
- network setup
- average `tx` / `block` size

publish performance numbers:
- min `latency`
- max `throughput`

# Capacity
for a given:
- average tx / block size

publish capacity numbers:
- max possible blocks created
- min free disk space required

**Comment by odeke-em** [comment]
Sorry for hijacking this issue @illya13, but I also have a question on how we should benchmark Ethermint, I see https://github.com/tendermint/ethermint/tree/master/tests/benchmarking
but unfortunately I don't yet know how to run it.

**Comment by adrianbrink** [comment]
This issue is three fold.

1. We need to decide on reasonable benchmarks that we want to run.
2. We need to implement those benchmarks and run them for every release candidate in the future.
3. We need to update the docs and readme with those benchmarks.

Current status:
1. Ilya's suggestions from above are reasonable and we should start with them.
2. There are initial benchmarking implementations in `tests/benchmarking`, however these should be expanded and integrated into the CI process.
3. Nothing has been updated yet.

These numbers should be published to our documentation. Please refer to #225 for the status of the new documentation.

**Comment by adrianbrink** [comment]
A good tool to investigate might be [blockbench](https://github.com/ooibc88/blockbench).

**Comment by jackzampolin** [comment]
This is a legacy issue. Closing this in favor of a new issue. Also this work (benchmarking) is happening right now
