### ISSUE TITLE
Formalise the scaling ideas

### ISSUE THREAD

**Issue by illya13** [cosmos/ethermint-archive#176]
It would be good to brainstorm and publish `ethermint` scaling ideas.
It might be some joint discussion with `geth` or it might pure `cosmos` style like having multiple `ethermint` networks joint by `cosmos`

**Comment by adrianbrink** [comment]
Depends on #158, since it will rely on IBC.

**Comment by adrianbrink** [comment]
@jaekwon , @ebuchman , @ethanfrey and me have a lot of ideas for how scaling works for zones with the hub and independently of the hub. We need to codify these ideas into `docs/architecture` so that every interested developer understands where we see ethermint in the future. Furthermore it will also help our process and hopefully solicit more ideas from the community.
