### ISSUE TITLE
Implement a sensible solution for clientVersion RPC endpoint

### ISSUE THREAD

**Issue by ratranqu** [cosmos/ethermint-archive#235]
`web3_clientVersion` jsonrpc call should return the version of Ethermint, and possibly also be capitalised (for consistency with Ethereum return values)?

Currently, this is what comes back:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":64}' http://localhost:8545
{"jsonrpc":"2.0","id":64,"result":"ethermint/darwin-amd64/go1.8.3"}
```

**Comment by odeke-em** [comment]
I've taken a look at this and so far I don't think we can add this in without intercepting a response from geth itself or modifying the source code for "github.com/ethereum/go-ethereum/rpc" (or at least our vendored version), since the source code in there binds to that port and processes those requests.
@ratranqu what's your use case for this request? IMO this isn't invoking Ethermint directly.

**Comment by adrianbrink** [comment]
@odeke-em Have you looked at `ethereum/api.go`. We do override the RPC endpoints quite a bit.

**Comment by odeke-em** [comment]
@adrianbrink yes I did take a look at ethereum/api.go and nothing in there that stands out yet.

**Comment by ratranqu** [comment]
@odeke-em: the first reason to request this is consistency with Ethereum in terms of how an Ethermint node identifies itself. The use case are mostly in the Ops space where you want to be able to track which nodes run what version of ethermint without having to keep track of that information somewhere else. 

Since that call already returns that it is an Ethermint node, the node type must be set somewhere already. The version seems to be missing, so that may not have been set already.

**Comment by zramsay** [comment]
https://github.com/cosmos/ethermint
