### ISSUE TITLE
Create a simple static website to showcase ethermint

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#253]
The website should contain no new content and should rather just point to already existing resources.

To start with it should contain three links:
- documentation from #225 
- code (links to the repo)
- contribute (links to rocket chat)

A good example of the type of website that we should have is [OpenMined](http://openmined.org/). Ideally we can take something very similar to the old OpenMined website before the rebranding.

The website itself can live at [ethermint.network](https://ethermint.network).

I have added a beginning to the [gh-pages branch](https://github.com/tendermint/ethermint/tree/gh-pages). It just needs to get ported to jekyll for deploys.

**Comment by adrianbrink** [comment]
@nylira What do you think about simplifying the website in this form?

**Comment by nylira** [comment]
<img width="342" alt="screen shot 2017-08-24 at 12 08 08" src="https://user-images.githubusercontent.com/172531/29649163-fe036350-88c4-11e7-8dff-ce6c8a21ef77.png">

It's up on the `gh-pages` branch, works for mobile and desktop. Didn't port it to Jekyll yet, will leave deployment to you because I have to work on cosmos-ui some more.

**Comment by adrianbrink** [comment]
https://jekyllrb.com/tutorials/convert-site-to-jekyll/

**Comment by zramsay** [comment]
it's been up for awhile
