### ISSUE TITLE
Document how staking happens for the COSMOS zone and as a free-standing zone

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/ethermint-archive#267]
Ethermint can be deployed in two scenarios.

1. As a cosmos zone that shares the validator set with the cosmos hub.
2. As a free-standing zone that may or may not connect to the cosmos hub with its own validator set.

The first scenario is straight-forward in that ethermint normally never has to worry about slashing. If a validator tries to cheat in this deployment, his app_hash will be different and people can use the normal cosmos evidence process to prove that he cheated.

In the second case ethermint needs to be aware and able to slash deposits. This functionality should be pulled in from the cosmos-sdk. This involves that anyone can submit proof to the ethermint instance, which then checks the proof and if there was cheating slashes the validator by updating the internal state. This will even allow us to use any ERC20 token as the staking token, since ethermint can proxy the slashing behaviour to a smart contract.

**Comment by rigelrozanski** [comment]
Under scenario 1) there is still a need to worry about slashing, I don't see why an ethermint validator can perform honestly with regards to their comsos-hub validation and dishonestly with regards to their ethermint validation. With this in mind we cannot "share" the validators stake for both the hub zone and ethermint zone (even if the same validator address) because that leaves open the nothing-at-stake problem for if the validator simultaneously acts maliciously on both blockchains.
With this in mind, scenario 1) and 2) are moreless identical, whether each network uses the same validators or not, slashing procedures must be implemented per-zone. 
Lastly, as you've alluded, an ethermint zone could be staked with any ERC20 token (or any token of value for that matter which is able to be processed by the zone). Although I believe that we should maintain this capability for staking to handle staking with any plugin, we ought to force all zones connected to the hub right now to stake with the atom token, as it is the native token to cosmos, and we can therefor mint new tokens for validator rewards. We additionally may wish to provide some validation rewards in a more-liquid currency which is incapable of being staked ("ante" train of thought from the retreat, I'll stop myself here)
Sidenote: @adrianbrink are you working on building ethermint as a COSMOS-SDK module? This way you can leverage the staking module that I'm creating right now
