### ISSUE TITLE
Failed to build on MacOS from source

### ISSUE THREAD

**Issue by melekes** [cosmos/ethermint-archive#357]
```
$ git clone ...
$ git checkout develop
$ make get_vendor_deps
$ make build
/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: library not found for -lcrt0.o

$ go version
go version go1.9.2 darwin/amd64

mac os 10.13.1 High Sierra
```

**Comment by adrianbrink** [comment]
I can reproduce this. 

It's new and probably happened because something in macOS changed.

It is discussed here: https://stackoverflow.com/questions/3801011/ld-library-not-found-for-lcrt0-o-on-osx-10-6-with-gcc-clang-static-flag#3801032

Just tested it with `go-ethereum` and that still builds. I have to investigate this further, but I'm betting on an update from Apple.
