### ISSUE TITLE
Design/Implement Tx Routing for SDK Tx Types (Non-Ethereum Tx)

### ISSUE THREAD

**Issue by alexanderbez** [cosmos/ethermint-archive#431]
Should be able to parse Txs and know how to route them to various handlers. Maybe based on the to address?

**Comment by AdityaSripal** [comment]
I think the way to deal with this is to only allow the Ethereum TX structure. We use RLP to decode the transaction.

We reserve certain Ethereum addresses for specific SDK handlers.

If a user wants to make a SDK Tx, they construct an Ethereum Tx structure with the `Recipient` address set to the address associated with the desired SDK handler.

The user then Amino encodes the SDK Tx and places the encoded bytes into the `Payload` attribute.

The SDK app has one high-level handler. When the `Recipient` address is one of the reserved SDK addresses, the payload gets amino decoded into an `auth.StdTx` struct and passed through an antehandler and the appropriate handler. I'm pretty sure we need to encode the Tx and not just the msg, because the Ethereum Tx signature may not match the required signatures of the SDK Tx. This antehandler will also have to run ValidateBasic on all Msgs inside the SDK tx, because it won't be run in baseapp as usual.
If the `Recipient` address is unreserved, it gets handled like a normal Ethereum Tx

Benefits:

- Have single Tx type passed into SDK app, which is essential because the TxDecoder is RLP instead of Amino
- Map from address => SDK Handler can be passed into handler constructor to allow flexible number of SDK Tx types during instantiation

**Comment by alexanderbez** [comment]
Great @AdityaSripal! I think this will work. Two things to ponder on:

1. We should allow these `Recipient` addresses that map to SDK handlers to be configurable and well-known/discoverable.
~~2. Not overlap with the Ethereum address space. i.e., Maybe add a prefix to the address? Ethereum addresses are 20 bytes, so this gives us a lot of flexibility.~~

**Comment by alexanderbez** [comment]
Blocked by #440

**Comment by AdityaSripal** [comment]
Technically, I don't think we need to reserve multiple addresses for SDK tx's. We can simply reserve a single Ethereum address, and then decode payload and route appropriately.

I think it's better to do that since users don't have to know what address is for what handler. If they want to send any supported SDK tx, send it to the SDK-reserved address.

**Comment by alexanderbez** [comment]
Correct, that'll decrease any confusion and complexity. Good idea 👍 . Thoughts on that `payload` structure?

**Comment by AdityaSripal** [comment]
The `payload` structure should be an amino encoded Tx. We can make our Tx struct a slightly modified version of `auth.StdTx`. We don't need a StdFee, since we can just pass in gas and amount from the Ethereum Tx. We also don't need memo.

The signatures should also probably be Ethereum-style signatures.

I'll put in an example sdk Tx struct once i have the PR up.

**Comment by alexanderbez** [comment]
Sounds good. I definitely think this is worthy of a more in depth discussion as far as what we need/want in the Tx.

**Comment by alexanderbez** [comment]
~~Also, I plan on starting #440 very soon. Not sure if that'll collide with anything you're currently doing.~~

**Comment by jackzampolin** [comment]
@alexanderbez and @AdityaSripal I know @zmanian expressed some opinions on this as well. If I remember properly he mentioned that there were 2 approaches here. We should talk about this in detail in our next weekly meeting.

**Comment by alexanderbez** [comment]
Indeed we should. I still think it'll help to get @AdityaSripal PR in review just so we can see what it looks like. Feel free to jot down your thoughts here as well @zmanian 👍

**Comment by jackzampolin** [comment]
It would be 💯awesome to have one of those approaches implemented. Glad you are working on this @AdityaSripal

**Comment by alexanderbez** [comment]
Closed by #451
