### ISSUE TITLE
Integrating with tendermint

### ISSUE THREAD

**Issue by madan-ideas2it** [cosmos/ethermint-archive#489]
How do we make the current ethermint integrate with already running tendermint node?

Firstly, is there any documentation on how to start the ethermint atleast?

**Comment by alexanderbez** [comment]
@madan-ideas2it, do you mean Ethermint 1.0 or the new iteration/version?

**Comment by madan-ideas2it** [comment]
Hope the older version of ethermint is archived as ethermint_bak but that is also not usable since it is not compatible with tendermint latest anymore. Hence i somehow want a basic running version of tendermint node communicating with ethermint node and talk via geth

**Comment by alexanderbez** [comment]
@madan-ideas2it, see #488. I have completed a stateDB integration which will ultimately result in an EVM SDK module. My next steps are to get a TM node hooked in (so you can finally run a ethermint daemon) and then be able to route and process txs.

I should have this done by this week if not next, so stay tuned. Otherwise, for experimental purposes, you can try and fiddle with getting 1.0 working (but now deprecated).

**Comment by madan-ideas2it** [comment]
@alexanderbez ok thanks

**Comment by jakeonchain** [comment]
@alexanderbez any update for integrating ethermint with tendermint? thanks

@madan-ideas2it have you got ethermint 1.0 working with tendermint? How can you do it? thanks

**Comment by alexanderbez** [comment]
@jakeonchain we are currently working actively on development. We're stages away from hooking up Tendermint.
